### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/math#4]
It would be nice to have complex numbers incorporated.

**Comment by littleredcomputer** [comment]
This is easily done since Apache Commons Math, which I'm already using, has a complex type in it. 

Unlike MIT Scheme, however, the Apache complex type is basically a pair of doubles. It works fine, but in MIT Scheme it's possible to have an "exact" complex number where the x and iy components are integers. Does your application need something like that? I hope not, because I have about convinced myself that you don't really need elements of Z[i] unless you're doing number theory.

MIT Scheme also has a read syntax for complex numbers that looks like 0+1i. That's slick, but in Clojure it's going to look like (complex 0 1), which will be stored as (0.0, 1.0) in Apache. Good enough IMO.

Also, Apache knows how to do all the complex trig, so I won't have to learn it again. If you want to watch me run like hell, just use the phrase "branch cut..."
